config/routes.rb
Rails.application.routes.draw do
  
  resources :jobs
  root 'jobs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

	def index
	  if params[:category].blank?
	    @job = Job.all.order('created_at DESC')
	  else
	  	@category_id = Category.find_by(name: params[:category]).id
	  	@job = Job.where(category_id: @category_id).order("created_at DESC")
	  end
	end

	def show
	end

	def new
	  @job = Job.new
	end

	def create
	  @job = Job.new(job_params)

	  if @job.save
	  	redirect_to @job
	  else
	  	render "New"
	  end
	end

	def edit
	end

	def update
	  if @job.update(job_params)
	  	redirect_to @job
	  else
	  	render "Edit"
	  end 
	end

	def destroy
	  @job.destroy
	  redirect_to root_path
	end


		private

		def job_params
		  params.require(:job).permit(:title, :description, :company, :url, :category_id)
		end

		def find_job
		  @job = Job.find(params[:id]) # D.R.Y. I'll be reusing this def more than once
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job, html: { class: 'form-horizontal' }) do |f| %>
	<%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category" }, input_html: { class: "dropdown-toggle" } %>  <!-- collect categories by id, and look through each -->
	<%= f.input :title, label: "Job Title", input_html: { class: "form-control" } %>
	<%= f.input :description, label: "Job Description", input_html: { class: "form-control" } %>
	<%= f.input :company, label: "Company's name", input_html: { class: "form-control" } %>
	<%= f.input :url, label: "Website's url", input_html: { class: "form-control" } %> <br/>

	<%= f.button :submit %>
	
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>  

app/views/jobs/index.html.erb
<div id="jobs">
  <% @job.each do |job| %>
    <div class="job">
      <h2>
        <%= link_to job.title, job %>
      </h2>
      <p>
        <%= job.company %>
      </p>
    </div>
  <% end %>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to "Back", root_path %>    

app/views/jobs/show.html.erb
<div id="jobs">
  <div class="job">
    <h2>
      <%= @job.title %>
    </h2>
    <p>
      <%= @job.description %>
    </p>
    <p>
      <%= @job.company %>
    </p>
    <button class="btn btn-default">
      <%= link_to "Apply for Job", @job.url %>
    </button>
  </div>
</div>
<div id="links">
  <%= link_to "Back", root_path, class: "btn btn-sm btn-default" %>
  <%= link_to "Edit", edit_job_path(@job), class: "btn btn-sm btn-default" %>
  <%= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-default" %>
</div>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                   <div class="navbar-brand"> <%= link_to "Tech Jobs", root_path %></div>
                </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
             <ul class="nav navbar-nav navbar-right">
                  <li>
          <%= link_to "All Jobs", root_path %>
        </li>
        <% Category.all.each do |category| %>
          <li>
            <%= link_to category.name, jobs_path(category: category.name) %>
          </li>
        <% end %>
      </ul>
      <%= link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link" %>
              </ul>
          </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav> <!-- nav end -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>JobsBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <div class="col-md-6 col-md-offset-3">

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert" %>
      <% end %>

      <%= yield %>
    </div>
  </div>


  </body>
</html>